#!/usr/bin/env python3
"""
Entry point for PyInstaller exe build.
This script properly handles resource paths for bundled exe.
"""
import sys
import os
import threading
import time
from pathlib import Path


def setup_logging():
    """Setup logging - write to file when no console"""
    if getattr(sys, 'frozen', False):
        exe_dir = Path(sys.executable).parent
        log_file = exe_dir / 'data' / 'server.log'
        log_file.parent.mkdir(parents=True, exist_ok=True)
        sys.stdout = open(log_file, 'a', encoding='utf-8')
        sys.stderr = sys.stdout


def get_resource_path(relative_path: str) -> Path:
    """Get absolute path to resource, works for dev and PyInstaller"""
    if getattr(sys, 'frozen', False):
        # Running as compiled exe
        base_path = Path(sys._MEIPASS)
    else:
        # Running in development
        base_path = Path(__file__).parent
    return base_path / relative_path


def setup_environment():
    """Setup environment before importing app modules"""
    if getattr(sys, 'frozen', False):
        # When running as exe
        exe_dir = Path(sys.executable).parent
        
        # Static files are bundled in _MEIPASS
        os.environ['PZ_STATIC_DIR'] = str(get_resource_path('static'))
        
        # Data directory next to exe
        data_dir = exe_dir / 'data'
        os.environ['PZ_DATA_DIR'] = str(data_dir)
        
        # Look for .env file next to exe
        env_file = exe_dir / '.env'
        if env_file.exists():
            from dotenv import load_dotenv
            load_dotenv(env_file)
    else:
        os.environ['PZ_STATIC_DIR'] = str(Path(__file__).parent / 'backend' / 'static')
        os.environ['PZ_DATA_DIR'] = str(Path(__file__).parent / 'data')
    
    # Ensure data directory exists
    data_dir = Path(os.environ['PZ_DATA_DIR'])
    data_dir.mkdir(parents=True, exist_ok=True)
    
    # Keys will be auto-generated by config.py when settings are loaded


def run_server(host: str, port: int):
    """Run uvicorn server in background thread"""
    import uvicorn
    import logging
    
    # Suppress most logging
    logging.getLogger("uvicorn.access").setLevel(logging.WARNING)
    logging.getLogger("uvicorn.error").setLevel(logging.WARNING)
    
    from app.main import app
    
    uvicorn.run(app, host=host, port=port, log_level="warning")


def wait_for_server(url: str, timeout: int = 30):
    """Wait for server to be ready"""
    import urllib.request
    import urllib.error
    
    for _ in range(timeout * 2):  # Check every 0.5s
        try:
            urllib.request.urlopen(f"{url}/api/health", timeout=1)
            return True
        except (urllib.error.URLError, urllib.error.HTTPError):
            time.sleep(0.5)
    return False


def main():
    setup_logging()
    setup_environment()
    
    from app.config import settings
    
    host = "127.0.0.1"  # Use localhost for webview
    port = settings.api_port
    url = f"http://{host}:{port}"
    
    # Start server in background thread
    server_thread = threading.Thread(target=run_server, args=(host, port), daemon=True)
    server_thread.start()
    
    # Wait for server to start
    if not wait_for_server(url):
        return
    
    # Open webview window
    try:
        import webview
        window = webview.create_window(
            'PZ Rcon Manager',
            url,
            width=1400,
            height=900,
            min_size=(800, 600)
        )
        webview.start()
    except ImportError:
        # Fallback to console mode if webview not available
        print(f"WebView not available, running in console mode")
        print(f"Open {url} in your browser")
        import uvicorn
        from app.main import app
        uvicorn.run(app, host=settings.api_host, port=port, log_level="info")


if __name__ == "__main__":
    main()
